export const STATUS = {
  TODO: "TODO",
  INPROGRESS: "INPROGRESS",
  INREVIEW: "INREVIEW",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
  REOPENED: "REOPENED"
}

export const PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",       
  CRITICAL: "CRITICAL"
}